### PR TITLE
feat: allow continuation of expander menu

### PR DESCRIPTION
**Pull request by DKhalil**
In our case this was needed for a multi-step autofill, where first you select a type to insert, and then do the actual search.

e.g.:

```
#type:ID
```

### CODE REVIEW

**Comment by primer-css** [comment]
:wave: Hello and thanks for pinging us! This issue or PR has been added to our inbox and a Design Infrastructure first responder will review it soon.
- :art: **If this is a PR that includes a visual change**, please make sure to add screenshots in the description or deploy this code to a lab machine with instructions for how to test.
- :fast_forward: **If this is a PR that includes changes to an interaction**, please include a [video recording](https://support.apple.com/en-us/HT208721) in the description.
- :warning: **If this is urgent**, please visit us in [#primer](https://github.slack.com/archives/CSGAVNZ19) on Slack and tag the first responders listed in the channel topic.

**Review by keithamus — COMMENTED** [review]
Would be great to see some tests and documentation for this feature. I'm struggling a little to figure out what this is supposed to do.

**Comment by DKhalil** [comment]
@keithamus added some documentation to the README and a few tests. I hope it's clearer now, but to re-iterate:

I want to enable something like this:

```
#pr:123
#issue:123
#commit:123
#project:1234
```

Where the first dropdown would show the various data types, following a second one that allows the search for the actual entries.

**Comment by DKhalil** [comment]
@keithamus Is there anything still left unclear or requiring further expansion?

**Review by keithamus — APPROVED** [review]
This LGTM

**Comment by DKhalil** [comment]
@keithamus fixed the breaking tests

**Comment by keithamus** [comment]
Thanks for your perseverance on this one @DKhalil

**Pull request merged**
